name: emotion_diary
description: AI-Driven Emotional Insight and Emotion Analysis Diary
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  fl_chart: ^0.68.0
  # PDF export
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
