name: emotion_diary
description: AI-Driven Emotional Insight and Emotion Analysis Diary
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^12.0.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.7.0
  flutter_local_notifications: ^19.5.0
timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/emojis/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/assetsapp_icon.png"
  remove_alpha_ios: true