// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFaaVt585sERrW66rQRJRuC91mgS9fdU',
    appId: '1:416637005676:web:010ce711c61c79c567cd49',
    messagingSenderId: '416637005676',
    projectId: 'emotionaldiaryapp',
    authDomain: 'emotionaldiaryapp.firebaseapp.com',
    storageBucket: 'emotionaldiaryapp.firebasestorage.app',
    measurementId: 'G-MFR1GK82KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFm3KbMrcHgkwLft-PtiNAnDc5tJJuPN4',
    appId: '1:416637005676:android:88e747e706c4a81267cd49',
    messagingSenderId: '416637005676',
    projectId: 'emotionaldiaryapp',
    storageBucket: 'emotionaldiaryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqoxK-8HCR9o-7XtO0BcrbIkE8HaDKvA',
    appId: '1:416637005676:ios:4d756df9e87d792c67cd49',
    messagingSenderId: '416637005676',
    projectId: 'emotionaldiaryapp',
    storageBucket: 'emotionaldiaryapp.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaqoxK-8HCR9o-7XtO0BcrbIkE8HaDKvA',
    appId: '1:416637005676:ios:4d756df9e87d792c67cd49',
    messagingSenderId: '416637005676',
    projectId: 'emotionaldiaryapp',
    storageBucket: 'emotionaldiaryapp.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLFaaVt585sERrW66rQRJRuC91mgS9fdU',
    appId: '1:416637005676:web:52066bc966bd580a67cd49',
    messagingSenderId: '416637005676',
    projectId: 'emotionaldiaryapp',
    authDomain: 'emotionaldiaryapp.firebaseapp.com',
    storageBucket: 'emotionaldiaryapp.firebasestorage.app',
    measurementId: 'G-KVZT8NWYFZ',
  );
}
